spring.application.name=badminton-score
# server.port default will use environment variable PORT when provided by hosting platforms (e.g., Replit, Fly.io)
server.port=${PORT:8080}
spring.thymeleaf.cache=false
